os:
  - linux

language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
    - python: "3.11"
    - python: "3.12"
    - python: "3.13"
    - python: nightly
    - python: pypy3
  allow_failures:
    - python: "3.13"
    - python: nightly
    - python: pypy3

install:
  - pip install -r dev-requirements.txt -r requirements.txt -r tests/requirements.txt
  - pip install python-coveralls

script:
  - flake8 .
  - mypy .
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
