os:
  - linux

language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
    - python: nightly
    - python: pypy3
  allow_failures:
    - python: "3.10"
    - python: nightly
    - python: pypy3

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mypy
  - pip install pep8-naming
  - pip install python-coveralls

script:
  - flake8 .
  - mypy .
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
