os:
  - linux

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - nightly

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mypy
  - pip install pep8-naming
  - pip install python-coveralls

script:
  - flake8 .
  - mypy .
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
